# Generated by Django 3.1.7 on 2021-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_customer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer2',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
