# Generated by Django 3.1.7 on 2021-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_customer2_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='join_date',
            field=models.DateField(default='timezone.now'),
        ),
        migrations.DeleteModel(
            name='Customer2',
        ),
    ]
