# Generated by Django 3.1.7 on 2021-03-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
    ]
