# Generated by Django 3.1.7 on 2021-04-08 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20210318_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='full_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 8, 19, 5, 32, 441549)),
        ),
        migrations.CreateModel(
            name='Customer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_1', models.CharField(max_length=200)),
                ('address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
