# Generated by Django 3.1.1 on 2020-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201016_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(default=0, max_length=5000000),
        ),
    ]
