# Generated by Django 3.1.2 on 2020-10-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_category_product2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product2',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='product2',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
