# Generated by Django 3.1.2 on 2020-10-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201028_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='pub_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='product2',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
