# Generated by Django 3.1.2 on 2020-10-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20201028_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
