# Generated by Django 3.1.2 on 2020-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_product2_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
