# Generated by Django 3.1.2 on 2020-10-28 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20201028_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product2',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='category',
            new_name='pro_category',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='desc',
            new_name='pro_desc',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='image',
            new_name='pro_image',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='price',
            new_name='pro_price',
        ),
        migrations.AddField(
            model_name='product2',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
