# Generated by Django 3.1.2 on 2020-10-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20201028_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product2',
            name='timestamp',
        ),
    ]
