# Generated by Django 3.1.2 on 2020-10-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_product2_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='item2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=50)),
                ('i_price', models.IntegerField(default=0)),
                ('i_desc', models.CharField(max_length=300)),
                ('i_image', models.ImageField(default='', upload_to='shop2/images2')),
                ('i_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
