# Generated by Django 3.1.7 on 2021-04-08 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20201029_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 8, 19, 5, 32, 430610)),
        ),
    ]
